/* Production shapes, taken verbatim from the 6 live library entries that
   already carry diagrams. Fixtures lie; these do not. */
const fs=require('fs');
const SC='/tmp/claude-0/-home-user-cardinal-inspections/39dffed8-e57b-5dc7-bbf7-dd9d3909112a/scratchpad';
function renderer(f){const s=fs.readFileSync(f,'utf8');
 const A="  function esc(s){ return String(s == null ? '' : s)\n    .replace(/&/g,'&amp;')";
 const B="    return '<p class=\"lb-p\">' + lbInline(lines.join('<br>')) + '</p>';\n  }";
 const a=s.indexOf(A),b=s.indexOf(B,a);
 return new Function(`var VIEW='v';var document={getElementById:function(){return null}};
 function ccIsAdmin(){return false};var window={currentUser:{email:'t@e.st'}};`+
 s.slice(a,b+B.length)+';return {lbRich:lbRich}')();}
const N=renderer(SC+'/app/index_v534.html'), O=renderer(SC+'/app/index_v533.html');
let p=0,f=0;const ok=(n,c,d)=>{c?(p++,console.log('  PASS  '+n)):(f++,console.log('  FAIL  '+n+(d?'\n          '+d:'')));};

// The attic entry's flow block, verbatim - note the stray "~~" fence line.
const ATTIC='- Verify soffit vents are open and unblocked by insulation, plywood decking, or paint.\n\n'+
 '~~flow\nCool outside air enters soffit vents\nAir flows up through rafter baffles\n'+
 'Warm moist air exhausts through ridge\n~~';
const a534=N.lbRich(ATTIC), a533=O.lbRich(ATTIC);
console.log('\nATTIC VENTILATION — the live entry with a stray ~~ fence');
/* STALE BY INTENT: before rule 4 these asserted "identical to 533" and
   "4 steps". Rule 4 deliberately changes this ONE entry, so the assertions
   are inverted rather than relaxed - the point is to prove the change is
   real and confined to it. */
ok('533 drew a bogus 4th step reading "~~"  [the live defect]',
   (a533.match(/class="lb-d-n"/g)||[]).length===4);
ok('534 draws 3 steps - the fence no longer becomes a row',
   (a534.match(/class="lb-d-n"/g)||[]).length===3,
   'steps drawn: '+(a534.match(/class="lb-d-n"/g)||[]).length);
ok('534 DIFFERS from 533 here, and only here', a534!==a533);
ok('it still draws a flow diagram', a534.indexOf('<svg')>-1);
ok('no "~~" text survives into the output', a534.indexOf('~~')===-1);

// The other five, spacing-wise: all correctly spaced already, so identical.
console.log('\nTHE OTHER FIVE — correctly spaced already, must be untouched');
const REAL=[
 ['parapet','| Fastener Spacing | 6 to 12 inches on center at term bar | Manufacturer Spec |\n\n~~stack\nMetal coping cap\nWaterproof membrane wrap\nWood nailer\nParapet masonry or wood wall\n\n## Proper Installation Steps'],
 ['standard details','- Ridge and soffit ventilation locations\n\n~~stack\nRoof shingles\nSynthetic underlayment\nIce & water barrier\nRoof deck sheathing\nRafter / Truss framing'],
 ['flashing types','## Sidewall Intersection Layering\n\n~~stack\nWall cladding / Siding\nStep flashing vertical leg\nShingle course\nSynthetic underlayment\nRoof deck sheathing\n'],
 ['diagram capabilities','Here is an example of a general roof assembly stack generated by the library:\n\n~~stack\nAsphalt Shingles\nSynthetic Underlayment\nIce & Water Shield\nDrip Edge Flashing\nRoof Deck Sheathing'],
 ['windows','- Apply self-adhering flashing tape over top flange and drip cap.\n\n~~stack\nHousewrap lapped over tape\nHead flashing tape\nMetal drip cap\nTop window flange\nWindow frame\n\n## Code & Egress Guidelines'],
];
for(const [n,s] of REAL){
  ok(n+': identical output', N.lbRich(s)===O.lbRich(s));
  ok(n+': still draws',      N.lbRich(s).indexOf('<svg')>-1);
}
console.log('\n'+'='.repeat(56)+'\n  '+p+' passed, '+f+' failed\n'+'='.repeat(56));
process.exit(f?1:0);
