#!/usr/bin/env python3
"""Regenerate /ai-field-manual.html from the authored book source.

The book is authored as a Claude Artifact, and the artifact host wraps what
you write in `<!doctype html><head><meta charset=utf8>…<body>` before serving
it. The authored file therefore starts at `<title>` with no doctype and no
charset — which is fine there and BROKEN the moment the same bytes are served
from Vercel: the browser guesses the encoding, and every em-dash renders as
`â€"` and every middot as `Â·`. That is what shipped on the first attempt, and
a screenshot is the only thing that caught it.

So the repo copy is generated, not copied. Re-run this after every book edit:

    python3 .claude/skills/cardinal-build/scripts/wrap_book.py <authored.html>
"""
import sys, os, re, tempfile

OUT = '/home/user/cardinal-inspections/ai-field-manual.html'

HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="referrer" content="no-referrer">
<meta name="robots" content="noindex,nofollow">
<meta name="color-scheme" content="light dark">
<!-- Generated by .claude/skills/cardinal-build/scripts/wrap_book.py — do not
     hand-edit. Edit the authored artifact, then re-run the script.
     noindex: the book is served publicly so the app can iframe it, but there
     is no reason for it to turn up in a search result. -->
<style>body{margin:0;padding:0}img{max-width:100%}</style>
"""

TAIL = "\n</body>\n</html>\n"


def main(srcpath):
    body = open(srcpath, encoding='utf-8').read()

    # the authored file opens with <title>…</title>; that belongs in the head
    m = re.match(r'\s*(<title>.*?</title>)\s*', body, re.S)
    title = m.group(1) if m else '<title>The AI Field Manual</title>'
    if m:
        body = body[m.end():]

    doc = HEAD + title + '\n</head>\n<body>\n' + body.rstrip() + TAIL

    # the wrap must not have introduced a second document
    assert doc.count('<!doctype html>') == 1, 'doctype not unique'
    assert doc.lower().count('<html') == 1 and doc.lower().count('</html>') == 1
    assert doc.count('<meta charset="utf-8">') == 1
    assert '<title>' in doc.split('</head>')[0], 'title escaped the head'
    # and must still be the whole book — count the sections rather than probe
    # for one, since 578 renumbered every chapter and data-ch="15" would have
    # gone on meaning "the last chapter" while silently meaning a different one
    n = doc.count('<section class="chapter')
    assert n == 21, f'{n} sections, want 21 (cover + 16 + 4 back)'
    assert 'data-ch="glossary"' in doc and 'data-ch="sources"' in doc, 'back matter lost'

    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(OUT))
    with os.fdopen(fd, 'w', encoding='utf-8') as f:
        f.write(doc)
    os.replace(tmp, OUT)
    print(f'ok  {srcpath} -> {OUT}  ({len(doc):,} chars, utf-8, doctype + charset)')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else
         '/tmp/claude-0/-home-user-cardinal-inspections/'
         'a9ea6de9-1097-5812-b046-748af1938962/scratchpad/ai-cheatsheet.html')
